# Generated by Django 4.2.2 on 2023-06-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_img_alter_product_name_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='product/placeholder.png', upload_to='products/', verbose_name='Фотография'),
        ),
    ]
