# Generated by Django 4.2.2 on 2023-06-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default='product/placeholder.png', upload_to='products/', verbose_name='Фотография'),
        ),
    ]
