# Generated by Django 4.2.2 on 2023-06-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(default='products/placeholder.png', upload_to='products/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='products/placeholder.png', upload_to='products/', verbose_name='Фотография'),
        ),
    ]
