# Generated by Django 4.2.2 on 2023-06-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='des',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
