# Generated by Django 4.2.2 on 2023-06-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_productinmodel_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_balance',
            field=models.IntegerField(default=0),
        ),
    ]
