# Generated by Django 4.2.2 on 2023-06-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_productinmodel_productinbasket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='summ',
            field=models.IntegerField(default=0),
        ),
    ]
