# Generated by Django 4.2.2 on 2023-06-10 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_favorites_favoriteproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteproduct',
            name='favorites',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.favorites'),
            preserve_default=False,
        ),
    ]
